[workspace]
resolver = "2"
members = [
    "framework",
    "app",
    "ferro-cli",
    "ferro-macros",
    "ferro-events",
    "ferro-queue",
    "ferro-notifications",
    "ferro-broadcast",
    "ferro-storage",
    "ferro-cache",
    "ferro-mcp",
    "ferro-inertia",
    "ferro-json-ui",
    "ferro-lang",
]

[workspace.package]
version = "0.1.79"
edition = "2021"
rust-version = "1.88.0"
license = "MIT"
