# syntax=docker/dockerfile:1.6
# Generated by `ferro docker:init` (Phase 122.2 §2). Edit freely; ferro will
# only overwrite this file when invoked with --force.
{{FRONTEND_STAGE}}
FROM rust:{{RUST_IMAGE_TAG}} AS chef
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends pkg-config libssl-dev ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install cargo-chef --locked

FROM chef AS planner
COPY . .
COPY Cargo.docker.toml Cargo.toml
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS backend-builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
COPY Cargo.docker.toml Cargo.toml
RUN cargo build --release
{{BIN_BUILDS}}

FROM debian:bookworm-slim AS runtime
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates libssl3 \
    && rm -rf /var/lib/apt/lists/*
{{RUNTIME_APT}}
{{BIN_COPIES}}
{{COPY_DIRS}}
EXPOSE 8080
