# Generated by ferro docker:init (ferro ref: {ferro_ref})
# Do not hand-edit; rerun ferro docker:init --force instead
{frontend_stage}
# ============ Stage: chef (cargo-chef base) ============
FROM {rust_base_image} AS chef
RUN cargo install cargo-chef
RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libssl-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ARG GITHUB_TOKEN=""
RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

# ============ Stage: planner ============
FROM chef AS planner
COPY Cargo.toml Cargo.lock ./
{workspace_copy_planner}
COPY src/ ./src/
COPY scripts/ ./scripts/
{ferro_rewrite_planner}
RUN cargo chef prepare --recipe-path recipe.json

# ============ Stage: backend-builder ============
FROM chef AS backend-builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json
COPY Cargo.toml Cargo.lock ./
{workspace_copy_builder}
COPY src/ ./src/
COPY scripts/ ./scripts/
{ferro_rewrite_builder}
RUN cargo build --release {cargo_build_bins}

# ============ Stage: runtime ============
FROM debian:bookworm-slim AS runtime
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*
{runtime_apt_block}
RUN useradd -m -u 1000 appuser
{runtime_bin_copies}
{runtime_optional_copies}
RUN mkdir -p storage/app/public && chown -R appuser:appuser storage
USER appuser
ENV APP_ENV=production
ENV SERVER_HOST=0.0.0.0
ENV SERVER_PORT=8080
EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/{entrypoint_bin}"]
