# Generated by `ferro ci:init` — edit freely; rerun with --force to regenerate.
# The api:check / validate:contracts steps shell out via `cargo run -p ferro-cli`
# so CI does not need a globally installed `ferro` binary.
name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry & target
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt --check
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo test
        run: cargo test --all-features

      - name: ferro api:check
        run: cargo run --quiet -p ferro-cli -- api:check

      - name: ferro validate:contracts
        run: cargo run --quiet -p ferro-cli -- validate:contracts
