# Rust
/target
Cargo.lock

# Node
frontend/node_modules
frontend/dist

# Build outputs
/public/assets

# Generated types (regenerated by ferro generate-types)
frontend/src/types/

# IDE
.idea
.vscode

# Environment
.env
.env.local
.env.*.local
