// This file is auto-generated by Ferro. Do not edit manually.
// Run `ferro generate-types` to regenerate.

// User type (shared across components)
export interface User {
  id: number;
  name: string;
  email: string;
}

export interface HomeProps {
  title: string;
  message: string;
}

// Authentication types
export interface LoginProps {
  errors?: Record<string, string[]>;
}

export interface RegisterProps {
  errors?: Record<string, string[]>;
}

export interface ForgotPasswordProps {
  status?: string;
  errors?: Record<string, string[]>;
}

export interface ResetPasswordProps {
  email: string;
  token: string;
  errors?: Record<string, string[]>;
}

export interface DashboardProps {
  user: User;
}

export interface ProfileProps {
  errors?: Record<string, string[]>;
}

export interface SettingsProps {
  settings?: {
    email_notifications: boolean;
    marketing_emails: boolean;
    theme: 'light' | 'dark' | 'system';
    language: string;
  };
  errors?: Record<string, string[]>;
}
