// =============================================================================
// Auto-generated by `ferro generate-types`
// Do not edit manually - changes will be overwritten
//
// To regenerate: ferro generate-types
// Auto-watch: ferro serve (types regenerate on file changes)
//
// For custom types not generated here, create manual type files in:
// frontend/src/types/
// =============================================================================

// Utility types

/** Represents any valid JSON value */
export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

/** Validation error messages keyed by field name */
export type ValidationErrors = Record<string, string[]>;

export interface HomeProps {
  title: string;
  message: string;
  user: HomeUser;
  stats: HomeStats;
}

export interface HomeStats {
  visits: number;
  likes: number;
}

export interface HomeUser {
  name: string;
  email: string;
}

