# Generated by ferro do:init — edit to your needs
# Ferro does not manage this file after initial scaffolding.
name: {{NAME}}
region: fra1

services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: {{REPO}}
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1

{{WORKERS_BLOCK}}
envs:
  # Set values in DO dashboard or via `doctl apps update`:
{{ENV_COMMENTS}}
