# DigitalOcean App Platform spec
# Generated by ferro do:init — do not hand-edit
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: {app_name}
region: {region}

services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: {github_repo}
      branch: main
      deploy_on_push: true
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-0.5gb
    instance_count: 1
    health_check:
      http_path: /_ferro/health
      initial_delay_seconds: 10
      period_seconds: 10
{envs_block}{workers_block}{databases_block}
