//! Generator for `scripts/rewrite-ferro-deps.sh` — the Docker-build-time
//! script that rewrites every `ferro*` path dep in a project's `Cargo.toml`
//! to a git dep pinned to `--ferro-ref`.
//!
//! Pure string composition. The only IO is reading the input `Cargo.toml`
//! to enumerate which `ferro*` crate names to target.

use std::fs;
use std::io;
use std::path::Path;
use toml::Value;

const FERRO_REPO: &str = "https://github.com/albertogferrario/ferro";

const DEP_TABLES: &[&str] = &["dependencies", "dev-dependencies", "build-dependencies"];

/// Render the full contents of `scripts/rewrite-ferro-deps.sh` for a project
/// rooted at the directory containing `cargo_toml`. See plan 122-02 interfaces.
pub fn render_rewrite_script(cargo_toml: &Path, ferro_ref: &str) -> io::Result<String> {
    let content = fs::read_to_string(cargo_toml)?;
    let crates = discover_ferro_path_deps(&content);

    let mut script = String::new();
    script.push_str("#!/usr/bin/env bash\n");
    script.push_str("# Generated by ferro docker:init — do not edit\n");
    script.push_str("set -euo pipefail\n");
    script.push('\n');
    script.push_str(&format!("FERRO_REF=\"{ferro_ref}\"\n"));
    script.push_str(&format!("FERRO_REPO=\"{FERRO_REPO}\"\n"));
    script.push('\n');
    script.push_str("CARGO_TOML=\"${1:-Cargo.toml}\"\n");
    script.push('\n');

    for crate_name in crates {
        script.push_str(&format!(
            "sed -i -E \"s|^({crate_name})\\s*=\\s*\\{{\\s*path\\s*=\\s*\\\"[^\\\"]+\\\"([^}}]*)\\}}|\\1 = {{ git = \\\"$FERRO_REPO\\\", branch = \\\"$FERRO_REF\\\"\\2}}|\" \"$CARGO_TOML\"\n"
        ));
    }

    Ok(script)
}

/// Walk the dependency tables of a parsed `Cargo.toml` string and collect every
/// key starting with `ferro` whose value is a table containing a `path` field.
/// Preserves insertion order, deduplicates. Returns empty Vec on parse failure.
fn discover_ferro_path_deps(content: &str) -> Vec<String> {
    let parsed: Value = match content.parse() {
        Ok(v) => v,
        Err(_) => return Vec::new(),
    };

    let mut out: Vec<String> = Vec::new();
    for table_name in DEP_TABLES {
        let Some(table) = parsed.get(*table_name).and_then(|v| v.as_table()) else {
            continue;
        };
        for (key, value) in table {
            if !key.starts_with("ferro") {
                continue;
            }
            let is_path_dep = value
                .as_table()
                .map(|t| t.contains_key("path"))
                .unwrap_or(false);
            if !is_path_dep {
                continue;
            }
            if !out.iter().any(|k| k == key) {
                out.push(key.clone());
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    fn write_cargo(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::new().unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    #[test]
    fn renders_sed_lines_for_each_ferro_path_dep() {
        let f = write_cargo(
            r#"
[dependencies]
ferro = { path = "../ferro/framework" }
ferro-json-ui = { path = "../ferro/ferro-json-ui" }
serde = "1"
"#,
        );
        let script = render_rewrite_script(f.path(), "main").unwrap();

        assert!(script.starts_with("#!/usr/bin/env bash\n# Generated by ferro docker:init"));
        assert!(script.contains("FERRO_REF=\"main\""));
        assert!(script.contains("# Generated by ferro docker:init"));
        assert!(script.contains("https://github.com/albertogferrario/ferro"));
        assert!(script.contains("(ferro)\\s*=\\s*\\{"));
        assert!(script.contains("(ferro-json-ui)\\s*=\\s*\\{"));
        assert!(!script.contains("(serde)"));
    }

    #[test]
    fn embeds_arbitrary_ferro_ref() {
        let f = write_cargo(
            r#"
[dependencies]
ferro = { path = "../ferro/framework" }
"#,
        );
        let script = render_rewrite_script(f.path(), "v0.1.87").unwrap();
        assert!(script.contains("FERRO_REF=\"v0.1.87\""));
    }

    #[test]
    fn no_sed_lines_when_zero_ferro_path_deps() {
        let f = write_cargo(
            r#"
[dependencies]
serde = "1"
tokio = { version = "1", features = ["full"] }
"#,
        );
        let script = render_rewrite_script(f.path(), "main").unwrap();
        assert!(script.starts_with("#!/usr/bin/env bash\n# Generated by ferro docker:init"));
        assert!(!script.contains("sed -i"));
    }

    #[test]
    fn errors_when_cargo_toml_missing() {
        let err = render_rewrite_script(Path::new("/nonexistent/Cargo.toml"), "main").unwrap_err();
        assert_eq!(err.kind(), io::ErrorKind::NotFound);
    }

    #[test]
    fn discovers_path_deps_across_dep_tables() {
        let f = write_cargo(
            r#"
[dependencies]
ferro = { path = "../ferro/framework" }

[dev-dependencies]
ferro-events = { path = "../ferro/ferro-events" }

[build-dependencies]
ferro-macros = { path = "../ferro/ferro-macros" }
"#,
        );
        let script = render_rewrite_script(f.path(), "main").unwrap();
        assert!(script.contains("(ferro)\\s*=\\s*\\{"));
        assert!(script.contains("(ferro-events)\\s*=\\s*\\{"));
        assert!(script.contains("(ferro-macros)\\s*=\\s*\\{"));
    }
}
